#pragma once

#ifndef UE_5_0_OR_EARLIER
#define UE_5_0_OR_EARLIER ((ENGINE_MAJOR_VERSION < 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION < 1))
#endif

#ifndef UE_5_2_OR_LATER
#define UE_5_2_OR_LATER ((ENGINE_MAJOR_VERSION > 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 2))
#endif

#ifndef UE_5_2_OR_EARLIER
#define UE_5_2_OR_EARLIER ((ENGINE_MAJOR_VERSION < 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION < 3))
#endif